draw_set_all(c_black, 0.5, fa_middle, fa_center, F_police_texte)
draw_rectangle(0, 0, room_width, room_height, false)
draw_self()
draw_set_alpha(1)
draw_text_transformed(x, y+decalage_texte, saut_ligne_str(texte, saut_ligne_carac), cam_sync_sc(1), cam_sync_sc(1), 0)