part_localb = part_type_create()
part_type_shape(part_localb, pt_shape_flare)
part_type_alpha3(part_localb, 0.8, 0.2, 0)
part_type_color2(part_localb, $00FFFF, $0000FF)
part_type_size(part_localb, 0.1, 0.2, 0, 0)
part_type_life(part_localb, 10, 30)
part_type_direction(part_localb, 0, 359, 0, 10)
part_type_speed(part_localb, 0.2, 0.5, 0, 0)

part_local = part_type_create()
part_type_shape(part_local, pt_shape_flare)
part_type_alpha3(part_local, 0, 0.8, 0)
part_type_color_rgb(part_local, 255, 255, 0, 255, 0, 0)
part_type_size(part_local, 0.5, 0.8, 0, 0)
part_type_life(part_local, 45, 150)
part_type_direction(part_local, 0, 359, 0, 0)
part_type_speed(part_local, 1.5, 4, 0, 0)
part_type_step(part_local, -3, part_localb)

part_sys_local = part_system_create()
part_system_depth(part_sys_local, depth)
part_emit = part_emitter_create(part_sys_local)
